### ISSUE TITLE
terminfo("all") lists spurious available terminals

### ISSUE THREAD

**Issue by d-lamb** [drzowie/PDL-Graphics-Gnuplot#38]
On a Linux machine, the following drivers are listed by terminfo(“all”) both as “Supported by PDL::Graphics::Gnuplot and your gnuplot” and “Supported by PDL::Graphics::Gnuplot but not your gnuplot”:

gif
grass
jpeg
pbm
pdf
png
windows

@Alien::Gnuplot::terms does not list any of those.

I think adding a line at 6768 "next unless($this->{valid_terms}->{$k});" just as at 6761 (for "DISPLAY TERMINALS") would fix this.

**Comment by drzowie** [comment]
Fixed.
