### ISSUE TITLE
Failure of test 36 "test plot has two curves"

### ISSUE THREAD

**Issue by d-lamb** [drzowie/PDL-Graphics-Gnuplot#42]
At revision d6a6bc7, I get a test failure at t/plot.t line 264:
~~~
not ok 36 - test plot has two curves". 
~~~
make test reports:
~~~
# P::G::G v2.005, gnuplot v5.0, Perl v5.016003, /opt/local/bin/perl5.16 on darwin #
~~~
The attached screenshot of a PDL shell manually walking through the steps shows the problem near the test failure: I think the problem is with '#' & '*' vs '+' & '-' for different Gnuplot versions.
![screen shot 2015-10-07 at 12 07 03 pm](https://cloud.githubusercontent.com/assets/6362944/10350277/5b5c3f32-6d00-11e5-9444-d0b9ff7f0c16.png)

**Comment by drzowie** [comment]
Fixed in github.  Test now checks for gnuplot v5.0, pl0 as a special and bizarre case (since its ascii plots were reverted in pl1).
