### ISSUE TITLE
option pager causes x11 detection fail in cygwin

### ISSUE THREAD

**Issue by devel-chm** [drzowie/PDL-Graphics-Gnuplot#55]
Apparently, the pager message when the terminfo types are more than one screen full causes detection of the x11 driver to fail.  I recently tried again directly from the bash shell prompt (same window) and the x11 detection succeeded.  Checking the difference between the environments running directly and under the cpan shell, I noticed that LINES=59 was set under CPAN.

If I did a 'LINES= make test' then tests pass for both cases.  This suggests that unsetting LINES when running the gnuplot instance for piping commands may resolve this issue.  Setting to a large number like 1000 seems to work as well...

**Comment by drzowie** [comment]
Thanks!  I now set LINES to a large number.
