### ISSUE TITLE
No quoting for output filenames.

### ISSUE THREAD

**Issue by amba** [drzowie/PDL-Graphics-Gnuplot#65]
Hi,

If I run

`my $gp = gpwin('dumb', output => 'somedir\somefile.txt');`

plot commands will send "set output "somedir\somefile.txt". On Windows, "somedir\somefile.txt" is equivalent to "somedirsomefile.txt". 
Apart from 'output', all of the other plot options use the quote_escape function to properly escape strings.

This means that on Windows you cannot use filenames generated with catfile etc. as output arguments.

I think this could be resolved by calling quote_escape on $vv just before
` return "set $k \"$vv\"\n";`
in line 5123.

**Comment by drzowie** [comment]
Thanks!  I’ll get this into git today.
