### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by amba** [drzowie/PDL-Graphics-Gnuplot#69]
Hey,

what about a release with the latest fixes? 
Would be great to have those on CPAN.

Best,
Simon

**Comment by jjatria** [comment]
Could maybe @dkogan or @devel-chm mint a new release instead? PDL::Graphics::Gnuplot is currently not installable from CPAN (at least for me), but the version currently on Github installs without any issues.

**Comment by mohawk2** [comment]
@drzowie Any chance?

**Comment by drzowie** [comment]
Sorry, this keeps floating down my to do list.  I will try to roll out a new release in the next day or two.  Moving forward, would one of you like to take over maintenance?

**Comment by mohawk2** [comment]
Seems to be my day for doing PDL stuff, so sure ;-)

**Comment by drzowie** [comment]
OK!  I’ll package up the release shortly and hand off to you in PAUSE.  What’s your PAUSE account, Mohawk?

**Comment by mohawk2** [comment]
ETJ. If you hand off to me, I can even do the releasing for you!

**Comment by drzowie** [comment]
OK, I released PDL-Graphics-Gnuplot 2.012 today.

**Comment by amba** [comment]
Many thanks!

 I will give it a test on Linux and Windows.

**Comment by mohawk2** [comment]
@drzowie Could you give me add me as a collaborator on this repo? Could you also commit and push to here the changes you made for the release? The repo seems to refer to _03 and _04, but CPAN doesn't have those. Also, what are your thoughts on transferring this repo over to PDLPorters?

**Comment by drzowie** [comment]
Okay, I”ve handed off the PAUSE ownership to ETJ.

**Comment by mohawk2** [comment]
@drzowie Sorry - it seems you've given me the PAUSE co-maint, but I can't push to this repo. Are you saying you want me to create a different one and point the metadata at that?

**Comment by drzowie** [comment]
Ah, I see.  You want PAUSE and also control of the github.  Stand by.

**Comment by drzowie** [comment]
OK, mohawk2 should now have push access.  I think github just sent you an invite.

I’m about to do the same for Alien-Gnuplot.

**Comment by mohawk2** [comment]
Got it, great!

And could you also push to here the changes you made in preparing the 2.012 release, so I don't have to recreate them from CPAN? :-)

**Comment by drzowie** [comment]
Sure.  

I’m on an airplane at the moment, so I’ll have to wait a few hours to re-push — but definitely.

**Comment by mohawk2** [comment]
Got the Alien invite too. Also to be able to release Alien::Gnuplot could I have co-maint on that too?

**Comment by mohawk2** [comment]
Re the push - great! Please ping on here then I can go through all the PRs on both of them :-)

**Comment by drzowie** [comment]
You mean on PAUSE?  Already done.

**Comment by mohawk2** [comment]
I was wrong to doubt you :-D

**Comment by mohawk2** [comment]
@drzowie Any idea of when you'll be able to push your latest work to the repo? I have a couple of quick and easy changes I'd like to make, but it would be a bit crazy to clash with yours!

**Comment by drzowie** [comment]
Done.

**Comment by mohawk2** [comment]
Thanks!

**Comment by mohawk2** [comment]
Final (hopefully) ask - could you enable Travis and AppVeyor on the repo, and/or enable me to do so? (If the latter I think you'd need to make me an admin)

**Comment by drzowie** [comment]
Hmmm.  I don’t see a way to enable you to add new collaborators — is there a permission list I don’t see?

**Comment by mohawk2** [comment]
I only need the CI (especially Travis) to be run. It's easiest if I have the ability to do that myself. I'm just looking to see how to enable me? But if you can just add the Travis etc, that would also be fine.

**Comment by drzowie** [comment]
What activates Travis?  Would it be a Webhook on push events?

**Comment by mohawk2** [comment]
I think it might be something re GitHub Apps? Still searching: https://github.com/travis-ci/travis-ci/issues/1390

**Comment by mohawk2** [comment]
Try https://github.com/drzowie/PDL-Graphics-Gnuplot/settings/installations

**Comment by drzowie** [comment]
I just tranferred ownership to you, mohawk2.

**Comment by mohawk2** [comment]
Seen, thanks! I'll put it under PDLPorters.

**Comment by drzowie** [comment]
Great.  PDL-Transform-Color should probably go there too, if you’re willing to take it.

**Comment by mohawk2** [comment]
Yes, go ahead. Please do the obvious with PAUSE too :-)

**Comment by drzowie** [comment]
PDL::Transform::Color is not yet on PAUSE, and you have everything else at this time.

**Comment by mohawk2** [comment]
Great!
